name: easy_arb_gen
description: csv_to arb gen
version: 1.0.1
repository: https://github.com/supunnilakshana/easy_arb_gen

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
    yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

